name: Build and Deploy to Develop
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build from Develop branch
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com
    steps:
      - name: Checkout Repox
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          envkey_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          envkey_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          envkey_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          envkey_APP_ID: ${{ secrets.APP_ID }}
          envkey_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID}}
          file_name: .env
      - name: Build
        run: npm run dev:build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy to Firebase Dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args:  deploy --only hosting --project dev
        env:
          name: dev
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
